# Generated by Django 3.0.7 on 2020-12-08 10:56

from django.db import migrations, models
import recommend.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('record', '0002_auto_20201208_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='View',
            fields=[
                ('view_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='景点编号')),
                ('view_name', models.CharField(max_length=100, verbose_name='景点名称')),
                ('view_score', models.FloatField(verbose_name='景点评分')),
                ('view_address', models.CharField(max_length=255, verbose_name='景点地址')),
                ('view_info', models.TextField(verbose_name='景点信息')),
                ('view_img', models.ImageField(upload_to=recommend.models.upload_path_View, verbose_name='景点照片')),
                ('collect_user', models.ManyToManyField(to='record.User')),
            ],
            options={
                'ordering': ['view_name'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='酒店编号')),
                ('hotel_name', models.CharField(max_length=100, verbose_name='酒店名称')),
                ('hotel_score', models.FloatField(verbose_name='酒店评分')),
                ('hotel_address', models.CharField(max_length=255, verbose_name='酒店地址')),
                ('hotel_info', models.TextField(verbose_name='酒店信息')),
                ('hotel_img', models.ImageField(upload_to=recommend.models.upload_path_Hotel, verbose_name='酒店照片')),
                ('hotel_kind', models.CharField(choices=[('Top', '高档型'), ('Comfortable', '舒适型'), ('Economical', '经济型')], default='Economical', max_length=50, verbose_name='酒店类型')),
                ('collect_user', models.ManyToManyField(to='record.User')),
            ],
            options={
                'ordering': ['hotel_name'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='餐饮编号')),
                ('food_name', models.CharField(max_length=100, verbose_name='餐饮名称')),
                ('food_score', models.FloatField(verbose_name='餐饮评分')),
                ('food_address', models.CharField(max_length=255, verbose_name='餐饮地址')),
                ('food_info', models.TextField(verbose_name='餐饮信息')),
                ('food_img', models.ImageField(upload_to=recommend.models.upload_path_Food, verbose_name='餐饮照片')),
                ('food_kind', models.CharField(choices=[('川湘菜', '川湘菜'), ('蛋糕甜食', '蛋糕甜食'), ('东北菜', '东北菜'), ('东南亚菜', '东南亚菜'), ('海鲜', '海鲜'), ('火锅', '火锅'), ('江浙菜', '江浙菜'), ('日韩料理', '日韩料理'), ('烧烤烤肉', '烧烤烤肉'), ('素食', '素食'), ('汤粥炖菜', '汤粥炖菜'), ('西餐', '西餐'), ('香锅烤鱼', '香锅烤鱼'), ('小吃快餐', '小吃快餐'), ('新疆菜', '新疆菜'), ('粤菜', '粤菜'), ('自助餐', '自助餐')], default='川湘菜', max_length=50, verbose_name='餐饮类型')),
                ('collect_user', models.ManyToManyField(to='record.User')),
            ],
            options={
                'ordering': ['food_name'],
            },
        ),
    ]
